language: java
jdk:
- oraclejdk11
- openjdk11
sudo: false
notifications:
  email: false
  slack:
    secure: rNEUCnaHUNZkoeMSyYQhMv7YBC+26YK6cwYm4SmrfwS2k17T5IGu+jBEPYwrs8hHoeV/ssjmeeVoCUYKX3jMyn6N1dtuw7sjHX0+PKVQmYoXiwsdYRGI240QXWDp+oTdSTHF6C7bE1JLlGTeJ9JdjLk4sBNblx3uhxuMv3MXxmssI2gvQJu8+UvOV4rrf32cfNJA1bKaSOOwFnwDjZN1nhUv/DLDDBdDLyPBVnyv8NTsaciwTm3xk32x6z8H/jCkDUQiPX8tXsb5k+JKovYqtlfPI5cuyoBHGLUyVagG02EolxRyc19cCEvEK5hQ2JPIFcSeQpLN+BEJK+GMpRYTMUtNGFxBvxjSxblgCzH+ZhyJx9H6wXk6I397EbeyHqawIX0h91iqXvIalE1FgmW12p+/Tqcx6GOloqs/eKK0PEN8axx5svKZ+ctaLyF4RIpNhbcd83es+19jjlslYpSP0O3b6rDojSJ8O2s85wmahu6qntdc42QwxrshOH4FNyU5dc0+KuHn5KntZ92CehZb2owLxV9ZOyUc69yua+stG6QGQG1GRNw/HRi3bRCfZ9y6+vtt1S0YdMR57J9Y2ibo1c47TYm0SgiXdmrAGqFSkYEcC6CYgf2G7ZTWwmXPvO1VCnBkH8gWKTufPexxsWdTInmVx1ZPX5Z+NXMp8mQr5II=
after_success:
- mvn clean test jacoco:report coveralls:report
deploy:
  provider: script
  script: mvn deploy --settings travis-settings.xml -DskipTests=true -B
  on:
    jdk: oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
