language: java
jdk:
- oraclejdk11
- openjdk11
sudo: false
notifications:
  email: false
  slack:
    secure: wFsTW9PxVGQqkT39UUhlGB5HmjKJ2gEKD2KC8bQ+40CkuBddEV+3c2LN3s307aFIlUGMclISG9JUbCtIy0/YxyQW4vv6ymrkbiHCtDnffWZQ9JYjwpDg7/cmZxdwA99RSrGjGfOPlqIikMC960jwnQlL3or8FFBg8qk9JYy0sChEgybjCm5V24L2Z+7mlibyeyOVRb2HKHz7cx1Q8izfe2JfXwrH5ccWlEJSK9em1/008fINGC/+mPp40mHY0J/g/ww9lPWPFVGvm8fQ13y6QxV86KZHb41RFrQEPJlrAwHhDG2HpKAyiXEagX8rc7SAM7mpf+2tJzG7t6JMbJCht6Maq2WrQ86GJs8it94ASHvL1JQZWJ9nH0xL3BHcquH6JpcpR9wpgi7KW6houFU38z6kwUY3/GxFQsKXITyOnN20EuKigHkz09MHCP3mWt2K4GSqV3PnhSF9qoLyd4upTMi9xPHmujwXm5nP50VB3lG1yx9w+toRuPDYcslA/FCdRqhqryJI2WBsLJ+s9U591VgN0vDUXVFOl9ajUw5s/rpEDhtLjR4EY2E7uXY1YbNnzJxse1qPgVC0EHxEp5qxJ5qqFC25N627JXJYIyiioNSqPh+0lZDlCXU3iYfIld4LfVBl5zDshjUJqxxEeboFPt+eO6c8E+DjhkOCScLdj8I=
    on_pull_requests: false
after_success:
- mvn clean test jacoco:report coveralls:report
deploy:
  provider: script
  script: mvn deploy --settings travis-settings.xml -DskipTests=true -B
  on:
    jdk: oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
