language: java
jdk:
- oraclejdk11
- openjdk11
sudo: false
notifications:
  email: false
  slack:
    secure: c5MtW/Ssk29HE8WzCvPIA7uY0FbzFLtfpm/oRmIkDms9lwjr5TD80u0x58nJvMX5uaWH2c5Umn9sEuPZzgydpo0PkG0E65+vi+TTPMhLw1ZFZpAcxr6BL/o9THkPPYOlRia4IN2WrQ6DoVtsmZDZRdzQbWriAXZF34iKwyvIEktLvaQnv5DGYUfmoYg31nyMB61eV0etRTw/mKgNXj1x89++QTmB0Pi/RoSU9PIEyJMDjC0POo6zFxl39mijjFgGq6nC5HQGUKSVKyFlYogQea82ZoVaYkaq0x+VHcEvzCNZUE8D+CK0/1MtijRJ7SI3QvOaaf/BkuQTXGKE0/lVKyfQPm6iMQm/QvNRz3ldx/FZEURj7k6vZdNcaX41BW+HQTF5unC2gUStN0XlSm4QwYh31o8MmOwwS0003058hnWVjLPK6maYn00NFWZ9zLWLSjOltgTGYZ8OcGmQKMS3JAsKG70EJMIurmBCujtw1fmNoDbk6Kf5EPM99WMu4OVEI4Q0lHirKYkKAt76iZselUeCVCnIN/DtTaTUBP7TlLrFMOasAUt+smludG1nUVa2u3LVLC8P961YigyaxWNsXT7CNlP5yiSavEu03wUtH+L8nNaOBr2ntrrmVB+CmfS0Tg/ukYWkGXWhSU6me6YKUkTV61ojgDuRgmF7pHO5XuU=
after_success:
- mvn clean test jacoco:report coveralls:report
deploy:
  provider: script
  script: mvn deploy --settings travis-settings.xml -DskipTests=true -B
  on:
    jdk: oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
